### ISSUE TITLE
Stackdriver Debugging GKE

### ISSUE THREAD

**Issue by HStuart18** [GoogleCloudPlatform/google-cloud-dotnet-debugger#376] opened 2018-12-05 05:38 UTC
So I am trying to enable Stackdriver Debugging with my ASP.NET Core application in Visual Studio 2017. I haven't created any PDB files myself, rather am just assuming the the ones Visual Studio produce will suffice (correct me if I'm wrong). Within VS GUI, I generated a Dockerfile and edited it to be:

    FROM gcr.io/dotnet-debugger/aspnetcore:2.0
    COPY . /app
    WORKDIR /app
    ENV STACKDRIVER_DEBUGGER_MODULE=module
    ENV STACKDRIVER_DEBUGGER_VERSION=1
    ENTRYPOINT ["/usr/share/dotnet-debugger/start-debugger.sh","dotnet", "telebot-pianomoves-v1.dll"]
Through Google Cloud Tools for VS, I published my application to a Google Kubernetes Engine cluster that had sufficient authorisation scopes. I also enabled the API in the GCP console.

When I opened the Stackdriver Debugging interface, it did seem to recognise my application as module-1. So I proceeded by uploading my local source code (specifially, the folder that contained my VS solution). The problem, is that when I click on a line to add a logpoint, the console shows Log points are currently not supported. and when I press on a line to add a snapshot, the console shows Waiting for snapshot to hit... and stays like that indefinitely.

Also, the API metrics console says that I am receving both 200 and 499 response codes.

Are these issues likely to arise from a problem with uploading source code? Is it my Dockerfile? PDB file? I can try and provide more specific information if it would help, but I didn't want to clog up the post with screenshots and I am hoping what is here is enough for someone to give me some direction.

Thank you so much!

***This is a post I made on Stackoverflow and was advised on raising an issue here on GitHub. This issue has been transferred from google-cloud tools for visual studio.

**Comment by iantalarico** [comment] 2018-12-05 15:49
@HStuart18 Thanks for moving the issue over here.  A few questions:

- Is it possible to share your .NET Core project? Or at minimum your csproj file?  If we have something to repo the issue with it makes it much easier for us to help.  We of course understand in many cases this is not possible.
- Just to be exhaustive.  What scopes does your GKE cluster have enabled?
- You said "Also, the API metrics console says that I am receving both 200 and 499 response codes."  Do you mean for Stackdriver Debugger API calls?  Could you share more details here?

A side not logpoints is currently not supported but will be in the near future.

**Comment by HStuart18** [comment] 2018-12-06 00:54
I am unfortunately not able to provide you with the full project, however, I can provide you with a modified project that hopefully is sufficient.

I am not sure how to check the scopes of a cluster, however, my nodes do have the scope `https://www.googleapis.com/auth/cloud_debugger`

These screenshots come from the Stackdriver Debugger API screen, after I deploy my project:

https://drive.google.com/open?id=13h_fmgo87a-eIir2IzC5jyBph-CjOJib

Thanks again!

**Comment by quoctruong** [comment] 2018-12-06 16:41
@HStuart18 Thank you very much for the details. I'll try to repro the bug with the project you provided.

**Comment by quoctruong** [comment] 2018-12-06 21:30
@HStuart18 I encountered some problem trying to build and compile the project.

For the Dockerfile, I think you are only copying all the files over (with no compilation).

Also, the entrypoint command that you are using may not be correct. The idea is that if I replace the last line with just `ENTRYPOINT ["dotnet", "telebot-pianomoves-v1.dll"]` instead of `ENTRYPOINT ["/usr/share/dotnet-debugger/start-debugger.sh","dotnet", "telebot-pianomoves-v1.dll"]`, then the app should just run normally. However, this wasn't the case, because I don't think `telebot-pianomoves-v1.dll` is in the folder `/app` on the Docker container.

So I think if you can get the correct `ENTRYPOINT` command (try building a Docker container without using our debugger yet), and then substitute it with `ENTRYPOINT ["/usr/share/dotnet-debugger/start-debugger.sh","<working command>"]`, the application should run.

**Comment by quoctruong** [comment] 2018-12-06 21:49
@HStuart18 I think your app may also requires `dotnet` command to be run in a specific folder (that contains some configuration file). I can add this feature to the debugger.

**Comment by HStuart18** [comment] 2018-12-07 01:12
Thanks for the response. Referring to your first point, what do you mean by copy all the files over without compilation and how would I fix this?

Within Visual Studio, I clicked on "generate Dockerfile" for the project and it created:

    FROM gcr.io/google-appengine/aspnetcore:2.0
    COPY . /app
    WORKDIR /app
    ENTRYPOINT ["dotnet", "telebot-pianomoves-v1.dll"]

I assume that this entrypoint is correct, since it was generated by VS when I deploy the application successfully to Google Kubernetes Engine. How would I modify this to use the debugger?

Cheers!

**Comment by quoctruong** [comment] 2018-12-07 02:21
Ah I see. I'm asking because normally when you run `dotnet` CLI to compile everything, assemblies are normally placed in `bin\Debug\netcore2.0` subfolder. So I was thinking that maybe `telebot-pianomoves-v1.dll` is not in the directly where you run `dotnet`.

So you can build, push and deploy the Dockerfile you mentioned above successfully?

**Comment by HStuart18** [comment] 2018-12-07 03:35
I have installed Google Cloud Tools for Visual Studio and from within the IDE, I deploy my application with this Dockerfile to my Kubernetes cluster successfully. So yes, the Dockerfile is built, pushed and deployed successfully.

**Comment by quoctruong** [comment] 2018-12-07 16:44
I see. How about when you deploy it with the`Dockerfile` that has `start-debugger.sh` in the Entrypoint? If the website is running with that Dockerfile too, then I think this may be caused by a bug (https://github.com/GoogleCloudPlatform/google-cloud-dotnet-debugger/issues/371) that we fixed recently. 

I was able to use the debugger with the app you provided on my local machine (using the bits that has the fix).

**Comment by quoctruong** [comment] 2018-12-10 19:08
@HStuart18, I was able to use the project you provided and set a snapshot at line 18 in `WebhookController.cs`. I didn't modify anything at all. I think it may be better if we set up a video call to help you address this?

**Comment by HStuart18** [comment] 2018-12-10 23:45
The problem must then be with how I select the source code. Was the source code immediately recognised in the Stackdriver Debugger for you and you set the snapshot from within the console? If not, what folder did you upload to the console to add the snapshot?

I live in Australia which may pose a slight inconvenience. I am available for the next few days to do a video call if the above questions don't seem to solve the problem.

Thanks!

**Comment by quoctruong** [comment] 2018-12-10 23:50
I just selected the `telebot-pianomoves-v1` folder (the one that contains `Controller` folder). Yes, the source code is recognized immediately. We can have a Hangout video call to solve this problem. I think anytime in the morning australian time will work.

**Comment by HStuart18** [comment] 2018-12-10 23:59
Interesting, I will play around for a bit longer today and see if I can figure out the problem. I can call tomorrow, Thursday of Friday at around 10am if one of those times works for you?

**Comment by quoctruong** [comment] 2018-12-11 00:19
10am tomorrow works for me. My email is quoct@google.com

**Comment by quoctruong** [comment] 2018-12-12 18:15
@HStuart18 Closing this issue since we were able to take snapshot. I investigated the issue around the startup code and I think there is a delay between startup and when the debugger can take the snapshot. Feel free to reopen this issue/contact me if you need any additional help.

**Closed by quoctruong** 2018-12-12 18:15 UTC
Labels: bug, p1
